const { Model, DataTypes } = require('sequelize');
const sequelize = require('../config/connection');

class Comment extends Model {}

Comment.init(
  {
    // id will be generated by sequelize
    body: {
        type: DataTypes.TEXT,
        allowNull: false,
    },
    date: {
      type: DataTypes.DATEONLY,
      allowNull: false,
      defaultValue: DataTypes.NOW
    },
  },{
    sequelize,
  }
);

module.exports = Comment;