const { Model, DataTypes } = require('sequelize');
const sequelize = require('../config/connection');

class Like extends Model {}

Like.init(
  {
    // Id will be generated by sequelize
    user: {
        type: DataTypes.STRING,
        allowNull: false,
        references: {
            model: 'Users',
            key: 'googleId',
        },
    },
    post_like: {
        type: DataTypes.BOOLEAN,
        allowNull: true,
        references: {
          model: 'Posts',
          key: '_id',
        },
    },
    comment_like: {
        type: DataTypes.BOOLEAN,
        allowNull: true,
        references: {
            model: 'Comments',
            key: '_id'
        }
    },
  },{
    sequelize,
  }
);

module.exports = Like;