const { Model, DataTypes } = require('sequelize');
const sequelize = require('../config/connection');

class Like extends Model {}

Like.init(
  {
    // Id will be generated by sequelize
    like: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
    }
  },{
    sequelize,
  }
);

module.exports = Like;